const fs = require ('fs');
const zlib = require ('zlib');
//const gzip = zlib.createGzip();
//const readStream = fs.createReadStream('./example.txt', 'utf8');
//const writeStream = fs.createWriteStream('./example2.gz');
//readStream.pipe(gzip).pipe(writeStream);
const gunzip = zlib.createGunzip();
const readStream = fs.createReadStream('./example2.gz');
const writeStream = fs.createWriteStream('compressed.txt','utf8');
readStream.pipe(gunzip).pipe(writeStream);